name: Release migrate-dashboard

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.28
      env:
        CGO_ENABLED: 1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # build and publish: linux/amd64
        goos: linux
        goarch: amd64
        goversion: https://dl.google.com/go/go1.18.linux-amd64.tar.gz
        pre_command: apt update && apt install -y gcc musl-dev
        binary_name: migrate-dashboard
        build_flags: -a
        ldflags: -linkmode external -extldflags -static -s -w
